version: '2'

vars:
    COMMIT_LINE: 'meme'

tasks:
    b:
        desc: "Build the blog to standart html and javascript bundle"
        cmds:
            - echo "The blog is now build"
            - bundle exec jekyll build
        silent: true

    
    s:
        desc: "Serve the blog at localhost for development, default port: 4000"
        cmds:
            - echo "The blog is now served"
            - bundle exec jekyll serve
        silent: true

    commit:
        cmds:
            - git add .
            - git commit -m {{ .COMMIT_LINE }}

    p:
        desc: "Push the blog source to remote repository"
        cmds:
            - task: commit
            - git push origin master
        silent: true


    fp:
        desc: "Publish the blog to remote website"
        cmds:
            - cd ./_site/
            - task: commit
            - git ftp push
        silent: true
            


