version: '2'

tasks:
        b:
                desc: build the drbinhthanh.com
                dir: $GEEK/drbinhthanh.com
                cmds:
                        - echo 'drbinhthanh.com''s blog will now build'
                        - bundle exec jekyll build
                silent: true
        s: 
                desc: serve the Dr. Ringo's blog
                dir: $GEEK/drbinhthanh.com
                cmds:
                        - echo 'drbinhthanh.com''s blog will now serve'
                        - bundle exec jekyll serve 
                silent: true
