version: '2'

tasks:
        build:
                desc: build the Dr. Ringo's blog
                dir: $GEEK/drbinhthanh.com
                cmds:
                        - echo 'Dr. Ringo''s blog will now build'
                        - bundle exec jekyll build
                silent: true
        serve: 
                desc: serve the Dr. Ringo's blog
                dir: $GEEK/drbinhthanh.com
                cmds:
                        - echo 'Dr. Ringo''s blog will now serve'
                        - bundle exec jekyll serve 
                silent: true
