version: '2'

vars:
    C: "default task commit line"

tasks:
    build:
        desc: "Build the blog to standart html and javascript bundle"
        cmds:
            - echo "The blog is now build"
            - bundle exec jekyll build
        silent: true
        
    serve:
        desc: "Serve the blog at localhost for development, default port: 4000"
        cmds:
            - echo "The blog is now served"
            - bundle exec jekyll serve
        silent: true

    commit:
        cmds:
            - git add .
            - git commit -m "{{ .C }}"

    push:
        desc: "Push the blog source to remote repository"
        cmds:
            - task: commit
              ignore_error: true
            - git push origin master
        silent: true


    publish:
        desc: "Publish the blog to remote website"
        cmds:
            - cd ./_site/
            - task: commit
              ignore_error: true
            - git ftp push
        silent: true
            
    b:
        deps: [build]
    s:
        deps: [serve]
    p:
        deps: [push]
    fp:
        deps: [publish]
